version number entry detailed in IANA section
markusa/ietf-multipath-dccp pull request #146
Opened 2022-09-09 11:12 UTC by dirkhugo

closes #118

2022-09-09 11:13 UTC, dirkhugo commented
@boucadair : Does this address your comment, Med?

2022-09-12 11:16 UTC, boucadair commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +As outlined in sect. {{mp_capable}} the new 1-Byte entry above includes a 4-bit part to specify the version of the used MP-DCCP implementation.
```suggestion
As outlined in sect. {{mp_capable}} the new 1-Byte entry above includes a 4-bit part to specify the version of the used MP-DCCP implementation. This document requests IANA to create a new sub-registry under the MP-DCCP registry to track the MP-DCCP version. The initial content of this sub-registry is as follows: 

<<<Table with the value that is assigned in this document + list of values for future assignments>>>
```

2022-09-14 13:01 UTC, dirkhugo reviewed
@boucadair : Addresses this text and format your comments? Thanks for clarification!

2022-09-14 13:10 UTC, boucadair requested changes

2022-09-14 13:10 UTC, boucadair commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +Future MP-DCCP versions 1 to 15 are assigned in this sub-registry using the Specification Required policy (Section 4.6 of {{RFC8126}}).
```suggestion
Future MP-DCCP versions 1 to 15 are assigned from this sub-registry using the Specification Required policy (Section 4.6 of {{RFC8126}}).
```

2022-09-14 13:10 UTC, boucadair commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +   |  Version  | Unassigned | Specification  |
```suggestion
   |  Version  | Description | Specification  |
```

2022-09-14 13:10 UTC, boucadair commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +   |   0000    |   0000     | [ThisDocument] |
```suggestion
   |   0000    |   Version 0| [ThisDocument] |
```

2022-09-14 13:10 UTC, boucadair commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +   |0001 - 1111|   0000     |      TBD       |
```suggestion
   |0001 - 1111|   Unassigned     |                 |
```

2022-09-14 13:29 UTC, dirkhugo commented
so we can close this issue, right? merci!

2022-09-14 13:44 UTC, boucadair commented
> so we can close this issue, right? merci!

I think so, thanks.

2022-09-14 13:44 UTC, merged