Notification of peer why path was discarded
markusa/ietf-multipath-dccp pull request #158
Opened 2022-09-14 14:56 UTC by markusa

Closes #121

2022-09-14 14:56 UTC, markusa commented
@boucadair, does this adress your issue #121?

2022-09-14 15:11 UTC, boucadair requested changes

2022-09-14 15:11 UTC, boucadair commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +e.g. during establishment, it is recommended to use a DCCP reset code as specified in
```suggestion
e.g., during subflow establishment, it is RECOMMENDED to use an appropriate DCCP reset code as specified in
```

2022-09-14 15:11 UTC, boucadair commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +Table 2 of {{RFC4340}}. This could be, for example, sending reset code 5 when an MP-DCCP
```suggestion
Table 2 of {{RFC4340}}. This could be, for example, sending reset code 5 (Option Error) when an MP-DCCP
```

2022-09-14 15:11 UTC, boucadair commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +option provides invalid data, or reset code 9 when the maximum number of maintainable paths
```suggestion
option provides invalid data or reset code 9 (Too Busy) when the maximum number of maintainable paths
```

2022-09-14 15:11 UTC, boucadair commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +is reached.
```suggestion
is reached. Note that receiving a reset code 9 for secondary subflows SHOULD NOT impact already existing active subflows. These subflows will be terminated following the procedure defined in Section XX, when needed. 
```

2022-09-14 15:41 UTC, markusa commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +is reached. Note that receiving a reset code 9 for secondary subflows SHOULD NOT impact already existing active subflows. These subflows will be terminated following the procedure defined in Section
@boucadair, 

1. `Note that receiving a reset code 9 for secondary subflows SHOULD NOT impact already existing active subflows.`

Not sure if I get your intention here, as this should be obvious already. If this note is required from your view, why this has not to be mentioned for reset code 5?

2. `These subflows will be terminated following the procedure defined in Section XX, when needed.`

If a remote host is Too Busy I don't see that this requires a special procedure. Either the remote host can keep ongoing active connections or remote host can decide to close individual subflows as outlined in this paragraph or close the whole MP-DCCP connection using MP_CLOSE or MP_FASTCLOSE.

I propose to remove both sentences.

2022-09-15 07:18 UTC, boucadair commented
There is no ambiguity for code 5 as the message validation will just fail, while for 9 it is better to be explicit that the peer is "busy" for this new subflow, but is still able to maintain already active subflows.

2022-09-15 08:36 UTC, merged