#170 nits and etc
markusa/ietf-multipath-dccp pull request #176
Opened 2022-11-30 11:28 UTC by shjohnson-bt

First stab at adding MP_PRIO example to MP_CONFIRM section as well as adding a new section on "Address knowledge exchange" containing further examples.

Hopefully I have interpreted the descriptions of MP_CONFIRM.MP_PRIO/MP_ADDADDR and MP_REMOVEADDR correctly!

Closes #170

2022-12-01 08:48 UTC, markusa approved these changes

2022-12-01 12:48 UTC, NathalieRM reviewed
Hi @shjohnson-bt
 
The structure of the diagrams and the description of the cases look quite good to me; however, I have a problem with the use of DCCP-Request and DCCP-Response packets to illustrate the transmission and confirmation of the mp_options. Given that the draft doesn't specify over which packet types should or must be sent these options, in theory, it is possible that an MP_PRIO option is sent over a DCCP-Request packet, but the scenario where the MP_PRIO is updated twice is not possible with 2 DCCP-Request packets (the second one would attempt to establish a new subflow). Furthermore, the draft only specifies that Data and Data-Ack packets must have MP_SEQ numbers, so, a DDCP-Request might or might not have a MP-SEQ number (which makes impossible the confirmation). 

In summary, my proposal would be to specify somewhere in he draft that these options (MP_PRIO, MP_ADDADDR, MP_REMOVEADDR and MP_CONFIRM) must be transmitted over Data or Data-Ack packets and modify this section accordingly.

2022-12-01 14:09 UTC, NathalieRM requested changes
I have reconsidered the use of DCCP-Request and DCC-Response, and I think at least in the first example for the MP_RRIO option, it is ok to use it (the use of MP_SEQ is mandatory for MP_PRIO, so you can ignore my previous concern about it), for the other scenarios I have made suggestions to change them to DCCP-Data and DCCP-Ack packets

2022-12-01 14:09 UTC, NathalieRM commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +* the leftmost 20 bytes of the HMAC(B) generated during the initial handshaking procedure {{handshaking}}
```suggestion
Host B acknowledges receipt of the MP_REMOVEADDR message with a DCCP-Ack containing the MP_CONFIRM option. The parameters supplied in this
response are as follows:
* an MP_CONFIRM containing the MP_SEQ number (seqno 33) of the packet carrying the option that we are confirming, together with the MP_REMOVEADDR option
* the leftmost 20 bytes of the HMAC(B) generated during the initial handshaking procedure {{handshaking}}
```

2022-12-01 14:09 UTC, NathalieRM commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +     |<----- MP_CONFIRM(seqno 33, MP_REMOVEADDR) ----------|
```suggestion
     |             |                                       |
     |   DCCP-Data +  MP_REMOVEADDR(id 2) +             |
     |------- MP_HMAC(A) + MP_SEQ(seqno 33) -------------->|
     |             |                                       |      
     |   DCCP-Ack + MP_HMAC(B) +                      |
     |<----- MP_CONFIRM(seqno 33, MP_REMOVEADDR) ----------|
```

2022-12-05 14:47 UTC, shjohnson-bt commented
Thanks Nathalie – the corrections make sense. I have accepted them and requested a re-review.

Kind Regards,
Stephen

From: NathalieRM ***@***.***>
Sent: Thursday, 01 December 2022 14:09
To: markusa/ietf-multipath-dccp ***@***.***>
Cc: Johnson,SH,Stephen,TUD2 R ***@***.***>; Mention ***@***.***>
Subject: Re: [markusa/ietf-multipath-dccp] #170 nits and etc (PR #176)


@NathalieRM requested changes on this pull request.

I have reconsidered the use of DCCP-Request and DCC-Response, and I think at least in the first example for the MP_RRIO option, it is ok to use it (the use of MP_SEQ is mandatory for MP_PRIO, so you can ignore my previous concern about it), for the other scenarios I have made suggestions to change them to DCCP-Data and DCCP-Ack packets

________________________________

In draft-ietf-tsvwg-multipath-dccp.mkd<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarkusa%2Fietf-multipath-dccp%2Fpull%2F176%23discussion_r1037106116&data=05%7C01%7Cstephen.h.johnson%40bt.com%7C65583fea8ff846d2d46808dad3a5a431%7Ca7f356889c004d5eba4129f146377ab0%7C0%7C0%7C638055005631479762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z2WuJbQ0%2FSkQakOwPKuVdBYPhbeOZJDlPZSRg1HpeVU%3D&reserved=0>:

> +Here, a first DCCP-Request is sent from Host A to Host B with option MP_PRIO set to 4. Host A subsequently issues a second DCCP-Request with option MP_PRIO



+set to 1. The delivery of the first MP_PRIO request is delayed in the network between Host A and Host B and arrives after the second MP_PRIO request. Host B



+ignores this second MP_PRIO request as the associated sequence number is earlier than the first. Host B sends a DCCP-Response confirming receipt of the MP_PRIO(1) with sequence number 2.


⬇️ Suggested change

-Here, a first DCCP-Request is sent from Host A to Host B with option MP_PRIO set to 4. Host A subsequently issues a second DCCP-Request with option MP_PRIO



-set to 1. The delivery of the first MP_PRIO request is delayed in the network between Host A and Host B and arrives after the second MP_PRIO request. Host B



-ignores this second MP_PRIO request as the associated sequence number is earlier than the first. Host B sends a DCCP-Response confirming receipt of the MP_PRIO(1) with sequence number 2.



+Here, a first DCCP-Data is sent from Host A to Host B with option MP_PRIO set to 4. Host A subsequently issues a second DCCP-Data with option MP_PRIO



+set to 1. The delivery of the first MP_PRIO is delayed in the network between Host A and Host B and arrives after the second MP_PRIO. Host B



+ignores this second MP_PRIO as the associated sequence number is earlier than the first. Host B sends a DCCP-Ack confirming receipt of the MP_PRIO(1) with sequence number 2.



________________________________

In draft-ietf-tsvwg-multipath-dccp.mkd<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarkusa%2Fietf-multipath-dccp%2Fpull%2F176%23discussion_r1037108596&data=05%7C01%7Cstephen.h.johnson%40bt.com%7C65583fea8ff846d2d46808dad3a5a431%7Ca7f356889c004d5eba4129f146377ab0%7C0%7C0%7C638055005631479762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=xlQT57pCrfktHtFOjMlhzuz2nSirsmNBETtjSXRLCZ0%3D&reserved=0>:

> +     |             |                                       |       |



+     |             |  DCCP-Request(seqno 1) +  MP_PRIO(4)  |       |



+     |             |-------------                          |       |



+     |             |             \                         |       |



+     |             |  DCCP-Request(seqno 2) +  MP_PRIO(1)  |       |



+     |             |---------------\------------------------------>|



+     |             |                \                      |       |



+     |             |                 ----------------------------->|



+     |             |                                       |       |



+     |             |  DCCP-Response +                      |       |



+     |             |<----- MP_CONFIRM(seqno 2, MP_PRIO) -----------|



+     |             |                                       |       |


⬇️ Suggested change

-     |             |                                       |       |



-     |             |  DCCP-Request(seqno 1) +  MP_PRIO(4)  |       |



-     |             |-------------                          |       |



-     |             |             \                         |       |



-     |             |  DCCP-Request(seqno 2) +  MP_PRIO(1)  |       |



-     |             |---------------\------------------------------>|



-     |             |                \                      |       |



-     |             |                 ----------------------------->|



-     |             |                                       |       |



-     |             |  DCCP-Response +                      |       |



-     |             |<----- MP_CONFIRM(seqno 2, MP_PRIO) -----------|



-     |             |                                       |       |



+     |             |                                       |       |



+     |             |  DCCP-Data(seqno 1) +  MP_PRIO(4)  |       |



+     |             |-------------                          |       |



+     |             |             \                         |       |



+     |             |  DCCP-Data(seqno 2) +  MP_PRIO(1)  |       |



+     |             |---------------\------------------------------>|



+     |             |                \                      |       |



+     |             |                 ----------------------------->|



+     |             |                                       |       |



+     |             |  DCCP-Ack +                      |       |



+     |             |<----- MP_CONFIRM(seqno 2, MP_PRIO) -----------|



+     |             |                                       |       |



________________________________

In draft-ietf-tsvwg-multipath-dccp.mkd<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarkusa%2Fietf-multipath-dccp%2Fpull%2F176%23discussion_r1037115091&data=05%7C01%7Cstephen.h.johnson%40bt.com%7C65583fea8ff846d2d46808dad3a5a431%7Ca7f356889c004d5eba4129f146377ab0%7C0%7C0%7C638055005631479762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=G86bVl%2FNQ1%2FzptDNJ3gK%2FirIIio38LHpWhik2GjSVIc%3D&reserved=0>:

> @@ -1199,6 +1245,68 @@ handshake is as follows:



 * Host B sends a DCCP-Ack to confirm the HMAC and to conclude the



   handshaking.







+## Address knowledge exchange



+### Advertising a new path ({{MP_ADDADDR}})



+



+When a host (Host A) wants to advertise the availability of a new path, it should use the MP_ADDADDR option ({{MP_ADDADDR}}) as



+shown in the example in {{ref-mp-dccp-add-address}}. The MP_ADDADDR option passed in the DCCP-Request contains the following parameters:



+* an identifier (id 2) for the new IP address which is used as a reference in subsequent control exchanges.



+* the IP address of the new path (A2_IP)



+* A pair of octets specifying the port number associated with this IP address. The value of 00 here, indicates that the port number is the same



+  as that used for the initial subflow address A1_IP



+



+This DCCP-Request must also supply:


⬇️ Suggested change

-This DCCP-Request must also supply:



+The following options must be included in a packet carrying MP_ADDADDR:



________________________________

In draft-ietf-tsvwg-multipath-dccp.mkd<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarkusa%2Fietf-multipath-dccp%2Fpull%2F176%23discussion_r1037121487&data=05%7C01%7Cstephen.h.johnson%40bt.com%7C65583fea8ff846d2d46808dad3a5a431%7Ca7f356889c004d5eba4129f146377ab0%7C0%7C0%7C638055005631479762%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV [...]

2023-02-06 14:59 UTC, abrunstrom commented
@NathalieRM Is this pull request ready? I think you requested changes but have not approved the updated version.

2023-02-06 15:09 UTC, NathalieRM approved these changes

2023-02-06 15:11 UTC, NathalieRM commented
Hi @abrunstrom, 

The pull request is ready. I just approved it.

2023-02-06 16:38 UTC, merged

2023-02-06 17:46 UTC, abrunstrom commented
Hi @markusa I saw you merged this pull request. I do not think Simone had reviewed it? My question to Nathalie was to understand if it was ready for review.

2023-02-06 17:51 UTC, markusa commented
@abrunstrom Correct, she did not confirm it here, but in the corresponding issue #170. That's why I merged the PR. Do you think that was wrong?

2023-02-06 20:21 UTC, abrunstrom commented
I understood the comment in #170 as "the plan looks good", but not sure she looked at the PR. She asked me if it was ready as Nathalie had requested changes and had not approved it yet. I have pinged her to find out, she can still look at the diff.

2023-02-07 09:16 UTC, abrunstrom commented
Simone has now also had a look at the updates. "The sequence diagrams that were added are a huge improvement", so well done :)

So all good to go now @markusa.

2023-02-07 09:20 UTC, markusa commented
Thank you @abrunstrom