Added text for closing a connection
markusa/ietf-multipath-dccp pull request #85
Opened 2022-06-16 08:57 UTC by shjohnson-bt

2022-06-20 08:45 UTC, markusa requested changes

2022-06-20 08:45 UTC, markusa commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +regular DCCP connection termination on each subflow with the first packet on
```suggestion
When a host wants to terminate the MP-DCCP connection regularly, it must initiate the 
standard DCCP connection termination on each subflow with the first packet on 
```
Proposed amendments to distinguish from MP_FAST_CLOSE.

2022-06-20 08:45 UTC, markusa commented on draft-ietf-tsvwg-multipath-dccp.mkd
> +Additionally, a MP-DCCP connection may be closed using the "Fast Close"
```suggestion
Additionally, a MP-DCCP connection may be closed abruptly - non regular - using the "Fast Close"
```

2022-06-20 10:19 UTC, shjohnson-bt commented
> **Question to the co-authors**: Would be flow diagrams as used in https://datatracker.ietf.org/doc/html/rfc8684.html#section-2.6 be useful?
> 
> ```
>       Host A                                 Host B
>       ------                                 ------
>       ACK + MP_FASTCLOSE          ->
>       [B's key]
> 
>       [RST on all other subflows] ->
> 
>                                   <-         [RST on all subflows]
> 
> 
>       Host A                                 Host B
>       ------                                 ------
>       RST + MP_FASTCLOSE          ->
>       [B's key] [on all subflows]
> 
>                                   <-         [RST on all subflows]
> ```

I think this would be helpful - should it go in this section or the respective MP_CLOSE or MP_FASTCLOSE sections?

2022-06-22 08:12 UTC, markusa approved these changes

2022-06-22 12:19 UTC, NathalieRM approved these changes

2022-06-22 12:26 UTC, merged